/*

  This file was generated by the Scratch2C transpiler.

  +----------------------------------------+
  | Please do not manually edit this file  |
  | as it was generated automatically!     |
  +----------------------------------------+

  Scratch2C Project
  Github: https://github.com/kadir014/scratch2c
  License: MIT

  Generated on: February 18, 2024 at 10:00 AM

  For support or issues, please use the issue tracker:
    https://github.com/kadir014/scratch2c/issues
  
*/

#include "scratch/scratch.h"


scProject project;


void sdl_init() {
    if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
	    fprintf(stderr, "SDL initialization error: %s\n", SDL_GetError());
        exit(EXIT_FAILURE);
	}

    if (TTF_Init() != 0) {
	    fprintf(stderr, "SDL_ttf initialization error: %s\n", TTF_GetError());
        exit(EXIT_FAILURE);
	}

    sc_uint32 img_init_flags = IMG_INIT_PNG | IMG_INIT_JPG;
    if (!(IMG_Init(img_init_flags) & img_init_flags)) {
	    fprintf(stderr, "SDL_image initialization error: %s\n", IMG_GetError());
        exit(EXIT_FAILURE);
	}
}

void sdl_quit() {
    SDL_Quit();
    TTF_Quit();
    IMG_Quit();
}


int main(int argc, char **argv) {
    project = scProject_default;

    sdl_init();

    SDL_Window *window = SDL_CreateWindow(
        "Scratch2C Window",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        project.stage_width,
        project.stage_height,
        SDL_WINDOW_SHOWN
    );
    if (!window) {
        fprintf(stderr, SDL_GetError());
        sdl_quit();
        return EXIT_FAILURE;
    }

    SDL_Renderer *renderer = SDL_CreateRenderer(
        window,
        -1,
        SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC
    );
    if (!renderer) {
        SDL_DestroyWindow(window);
        sdl_quit();
        fprintf(stderr, SDL_GetError());
        return EXIT_FAILURE;
    };

    SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

    scSprite target0 = {
        .x=0.0,
        .y=0.0,
        .angle=0.0,
        .visible=true,
        .draggable=true,
        .current_costume = 0
    };

    sdl_quit();
    
    return EXIT_SUCCESS;
}