/*

  This file was generated by the Scratch2C transpiler.

  +----------------------------------------+
  | Please do not manually edit this file  |
  | as it was generated automatically!     |
  +----------------------------------------+

  Scratch2C Project
  Github: https://github.com/kadir014/scratch2c

  Generated on: 04/03/2024 at 11:29:54

  For support or issues, please use the issue tracker:
    https://github.com/kadir014/scratch2c/issues
  
*/
    
#include "scratch/scratch.h"


/* Global project configuration */

scProject project;
scEngine *engine;


/**
 * @brief Convert Scratch coordinates to screen space. 
 * 
 * @warning Don't call this without initializing global project variable first.
 * 
 * @param x X
 * @param y Y
 */
static inline void SC_FASTCALL sc_scratch_to_screen_space(sc_real *x, sc_real *y) {
    *x += project.stage_width2;
    *y = -(*y) + project.stage_height2;
}


int main(int argc, char **argv) {
    project = scProject_default;
    project.metadata.scratch_ver = "3.0.0";
    project.metadata.vm_ver = "0.2.0";
    project.metadata.user_agent = "";
    engine = scEngine_new(project);

    project.targets_size = 2;
    scSprite targets[2];
    project.targets = targets;
    
    targets[0] = (scSprite){
        .is_stage=1,
        .x=0,
        .y=0,
        .angle=90,
        .visible=1,
        .draggable=0,
        .current_costume = 0
    };
    targets[0].max_costumes = 1;
    targets[0].costumes[0] = scCostume_load(engine->renderer, "project_data/cd21514d0531fdffb22204e0ec5ed84a.svg");

    targets[1] = (scSprite){
        .is_stage=0,
        .x=0,
        .y=0,
        .angle=174.89999999999998,
        .visible=1,
        .draggable=0,
        .current_costume = 0
    };
    targets[1].max_costumes = 1;
    targets[1].costumes[0] = scCostume_load(engine->renderer, "project_data/592bae6f8bb9c8d88401b54ac431f7b6.svg");

    engine->is_running = true;
    while (engine->is_running) {
        scEngine_tick(engine);

        scEngine_clear(engine);

        // Run scripts
        target2616643568208_flag_clicked2616643568464(&project.targets[1]);

        scEngine_render(engine, &project);

        scEngine_flush(engine);
    }

    scEngine_free(engine);
    
    return EXIT_SUCCESS;
}
