/*

  This file was generated by the Scratch2C transpiler.

  +----------------------------------------+
  | Please do not manually edit this file  |
  | as it was generated automatically!     |
  +----------------------------------------+

  Scratch2C Project
  Github: https://github.com/kadir014/scratch2c
  License: MIT

  Generated on: February 18, 2024 at 10:00 AM

  For support or issues, please use the issue tracker:
    https://github.com/kadir014/scratch2c/issues
  
*/

#include "scratch/scratch.h"


/* Global project configuration */

scProject project;
scEngine *engine;


/* Global (stage) variables */

scVariable g_var;


/* Custom blocks (procedures) */

static inline void SC_FASTCALL SomeCustomBlock(scVariable a, scVariable b) {
    if (b.value_int) {
        g_var.value_real = a.value_real;
    }
}


int main(int argc, char **argv) {
    project = scProject_default;
    engine = scEngine_new(project);

    scSprite target0 = {
        .x=0.0,
        .y=0.0,
        .angle=0.0,
        .visible=true,
        .draggable=true,
        .current_costume = 0
    };
    target0.max_costumes = 1;
    target0.costumes[0] = (scCostume){
        .filename="asset.png",
        .texture=NULL
    };

    bool is_running = true;

    double clock_frequency = (double)SDL_GetPerformanceFrequency();
    double clock_start = (double)SDL_GetPerformanceCounter() / clock_frequency;

    int mouse_x = 0;
    int mouse_y = 0;
    bool mouse_pressed = false;

    while (is_running) {
        double clock_timer = (double)SDL_GetPerformanceCounter() - clock_start;

        sc_uint32 mouse_state = SDL_GetMouseState(&mouse_x, &mouse_y);
        mouse_pressed = mouse_state & SDL_BUTTON(1) | 
                        mouse_state & SDL_BUTTON(2) | 
                        mouse_state & SDL_BUTTON(3);

        SDL_Event event;
        while (SDL_PollEvent(&event) != 0) {
            if (event.type == SDL_QUIT)
                is_running = false;
        }

        SDL_SetRenderDrawColor(engine->renderer, 255, 255, 255, 255);
        SDL_RenderClear(engine->renderer);

        printf("days since 2000: %.9f\n", sc_days_since_2000());

        SDL_RenderPresent(engine->renderer);
    }

    scEngine_free(engine);
    
    return EXIT_SUCCESS;
}