/*

  This file was generated by the Scratch2C transpiler.

  +----------------------------------------+
  | Please do not manually edit this file  |
  | as it was generated automatically!     |
  +----------------------------------------+

  Scratch2C Project
  Github: https://github.com/kadir014/scratch2c
  License: MIT

  Generated on: February 18, 2024 at 10:00 AM

  For support or issues, please use the issue tracker:
    https://github.com/kadir014/scratch2c/issues
  
*/
    
#include "scratch/scratch.h"


/* Global project configuration */

scProject project;
scEngine *engine;


/* Global (stage) variables */

scVariable var;
static inline void SC_FASTCALL SomeCustomBlock() {
    if (b) {SetVariable}
}
